### ISSUE TITLE
Limit for *One* functions?

### ISSUE THREAD

**Issue by EagleMoor** [AlekSi/reform#16]
`tail` needed for `WHERE or LIMIT` part of query. But function, whitch return just one struct need auto add `limit 1` automatically.

**Comment by AlekSi** [comment]
`FindOneFrom` and `FindOneTo` already use `LIMIT 1`. It is not possible to add it to tail automatically for `SelectOneFrom` and `SelectOneTo`. For example, consider tails `LIMIT 1 OFFSET 10` and `WHERE name = 'LIMIT 1'`. To figure out that `LIMIT 1` can be added to the second query, but not to the first, reform have to parse it, and I don't plan to add parser.
