### ISSUE TITLE
Schema support

### ISSUE THREAD

**Issue by EagleMoor** [AlekSi/reform#17]
Table & View need support schema prefix if need use it.
Example, we have same table in _public_ schema & same table in _chunks_ schema.
If we try change `Name` like this
```go
func (v *personeView) Name() string {
	return "public.persone"
}
```
we have sql like a `SELECT public.persone.id, public.persone.name, ...`

**Comment by AlekSi** [comment]
Use `//reform:public.persone` magic comment.
