### ISSUE TITLE
NewStruct() reform.Struct

### ISSUE THREAD

**Issue by EagleMoor** [AlekSi/reform#19]
Why `NewStruct` return `reform.Struct` if we have our struct, which implement `reform.Struct`?

https://github.com/AlekSi/reform/blob/master/reform/template.go#L45

**Comment by AlekSi** [comment]
Because `NewStruct() *Foo` doesn't matches signature `NewStruct() reform.Struct`, therefor `*FooTable` will not implement `reform.View` interface.

**Comment by EagleMoor** [comment]
I think that a particular table or twist must return a specific model, rather than an abstract. This is logical and convenient for the further use of this structure.

```go
// foo is Foo, not reform.Struct
foo := FooView.NewStruct()

func useFoo(f Foo) {
}
```

**Comment by AlekSi** [comment]
It will not work in Go. For example, see https://github.com/AlekSi/reform/blob/master/querier_selects.go#L67 Here we need `reform.View`, and `*FooView` will not implement it (see my previous comment).

In you case you need this:
```go
var foo Foo
```
That's it, no need to use `NewStruct()`.

**Comment by EagleMoor** [comment]
Thanks
